name: gce
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9.0
  - mkl<2022
  - pandas
  - numpy
  - tqdm
  - pygod
  - pytorch=2.0
  - torchvision=0.15.2
  - torchaudio=2.0
  - pyg
  - pytorch-sparse
  - jupyterlab
  - yfinance
  - matplotlib
  - openpyxl
  - ipywidgets
  - cvxopt
  - dropbox
  - networkx
  - seaborn
  - dgl
  - pip
  - pip:
    - torch-geometric
    - torch-geometric-temporal
