name: gce
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
  - pip
dependencies:
  - python=3.10.0
  - mkl < 2022
  - pandas
  - numpy
  - tqdm
  - tensorflow
  - tensorflow-probability
  - pyg-lib
  - pygod
  - pytorch=2.2.2
  - torchvision=0.17.2 
  - torchaudio=2.2.2
  - pyg 
  - pytorch-sparse 
  - jupyterlab
  - yfinance
  - matplotlib
  - openpyxl
  - ipywidgets
  - cvxopt
  - dropbox
  - networkx
  - seaborn
  - dglteam
  - dgl
  - pip:
    - torch-geometric
    - torch-geometric-temporal
