name: gce
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.10.0
  - mkl<2022
  - pandas
  - numpy
  - tqdm
  - tensorflow
  - tensorflow-probability
  - pyg-lib
  - pygod
  - pytorch=2.0  # Ensure this is a valid version
  - torchvision=0.15.2  # Ensure this matches the PyTorch version
  - torchaudio=2.0  # Ensure this matches the PyTorch version
  - pyg
  - pytorch-sparse
  - jupyterlab
  - yfinance
  - matplotlib
  - openpyxl
  - ipywidgets
  - cvxopt
  - dropbox
  - networkx
  - seaborn
  - dgl
  - pip
  - pip:
    - torch-geometric
    - torch-geometric-temporal
