python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed False --dataset_name simulation1c --graph_name erdos_renyi --k 1
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed False --dataset_name simulation1c --graph_name watts_strogatz --k 1
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name erdos_renyi --k 2
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name watts_strogatz --k 2
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name erdos_renyi --k 3
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name watts_strogatz --k 3
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name erdos_renyi --k 4
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_prerprocessed True --dataset_name simulation1c --graph_name watts_strogatz --k 4
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name erdos_renyi --k 5
python run_SpectrumExpanded.py  --sample False --model_name spectrumEx --load_preprocessed True --dataset_name simulation1c --graph_name watts_strogatz --k 5
