python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 20 --n_layers_enc 1 --n_layers_dec 1 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 30 --n_layers_enc 1 --n_layers_dec 1 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 40 --n_layers_enc 1 --n_layers_dec 1 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 50 --n_layers_enc 1 --n_layers_dec 1 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 1 --n_layers_dec 1 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 5 --n_layers_dec 5 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 10 --n_layers_dec 10 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 15 --n_layers_dec 15 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 20 --n_layers_dec 20 --epochs 10
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 20 --n_layers_enc 1 --n_layers_dec 1 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 30 --n_layers_enc 1 --n_layers_dec 1 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 40 --n_layers_enc 1 --n_layers_dec 1 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 50 --n_layers_enc 1 --n_layers_dec 1 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 1 --n_layers_dec 1 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 5 --n_layers_dec 5 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 10 --n_layers_dec 10 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 15 --n_layers_dec 15 --epochs 100
python run_SDNE_new1.py --model_name sdne-new1 --sample False --n_hidden 100 --n_layers_enc 20 --n_layers_dec 20 --epochs 100
